graph TD
    A[基本国策：每天早上起床后在十分钟内浏览所有国策，并添加一个新的国策或修改一个现有国策。]
    A --> B[每天吃 Vitamin D3、综合维生素和锌]
    B --> BA[洗完衣服后立即烘干，烘干完衣服后立即收好]
    BA --> BAA[每次吃完饭后立即收拾碗筷]
    A --> C[周中起床后的三十分钟内不用电子设备观看视频或阅读娱乐性文字]
    A --> D[每周给狗蛋剪指甲]
    D --> DA[每两天清理猫砂盆]
