graph TD
    A[基本国策：每天早上起床后在十分钟内浏览所有国策，并添加一个新的国策。]
    A --> B[每天吃 Vitamin D3、综合维生素和锌]
    B --> BA[洗完衣服后立即烘干，烘干完衣服后立即收好]
    BA --> BAA[每次吃完饭后立即收拾碗筷]
    B --> BB[每次洗完澡之后称体重]
    A --> C[周中起床后的三十分钟内不用电子设备进行娱乐性活动]
    A --> D[每周给狗蛋剪指甲]
